
import { PlotRecord, User, UserRole } from '../types';

// Mock Users with Passwords for Vercel/Demo mode
export const MOCK_USERS: (User & { password?: string })[] = [
  { 
    id: '1', 
    username: 'admin', 
    email: 'admin@cidco.com', 
    role: UserRole.ADMIN, 
    name: 'System Admin',
    password: 'admin' // Simple password for demo
  },
  { 
    id: '2', 
    username: 'user', 
    email: 'user@cidco.com', 
    role: UserRole.USER, 
    name: 'Demo User',
    password: 'user'
  },
];

// Mock Records - Expanded for realistic charts
export const MOCK_RECORDS: PlotRecord[] = [
  {
    ID: '101',
    NAME_OF_NODE: 'PANVEL EAST',
    SECTOR_NO_: '12',
    BLOCK_ROAD_NAME: 'Block A',
    PLOT_NO_: '55',
    PLOT_NO_AFTER_SURVEY: '55/A',
    SUB_PLOT_NO_: '',
    UID: 'UID-2023-001',
    DATE_OF_ALLOTMENT: '2010-05-15',
    NAME_OF_ORIGINAL_ALLOTTEE: 'Rahul Sharma',
    PLOT_AREA_SQM_: '500.00',
    PLOT_AREA_FOR_INVOICE: '500.00',
    PLOT_USE_FOR_INVOICE: 'RESIDENTIAL',
    USE_OF_PLOT_ACCORDING_TO_FILE: 'RESIDENTIAL',
    Department_Remark: 'Clear',
    Additional_Plot_Count: '0',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80'],
    has_pdf: true,
    has_map: false
  },
  {
    ID: '102',
    NAME_OF_NODE: 'PANVEL EAST',
    SECTOR_NO_: '12',
    BLOCK_ROAD_NAME: 'Block B',
    PLOT_NO_: '12',
    PLOT_NO_AFTER_SURVEY: '12',
    SUB_PLOT_NO_: '',
    UID: 'UID-2023-002',
    DATE_OF_ALLOTMENT: '2012-08-20',
    NAME_OF_ORIGINAL_ALLOTTEE: 'Priya Patel',
    PLOT_AREA_SQM_: '1200.00',
    PLOT_AREA_FOR_INVOICE: '1200.00',
    PLOT_USE_FOR_INVOICE: 'COMMERCIAL',
    USE_OF_PLOT_ACCORDING_TO_FILE: 'COMMERCIAL',
    Department_Remark: 'Encroachment',
    Additional_Plot_Count: '1',
    images: [],
    has_pdf: false,
    has_map: true
  },
  {
    ID: '103',
    NAME_OF_NODE: 'AIROLI',
    SECTOR_NO_: '5',
    BLOCK_ROAD_NAME: 'Road 3',
    PLOT_NO_: '7',
    PLOT_NO_AFTER_SURVEY: '7',
    SUB_PLOT_NO_: '',
    UID: 'UID-2023-003',
    DATE_OF_ALLOTMENT: '2015-01-10',
    NAME_OF_ORIGINAL_ALLOTTEE: 'Tech Solutions Ltd',
    PLOT_AREA_SQM_: '2500.00',
    PLOT_AREA_FOR_INVOICE: '2500.00',
    PLOT_USE_FOR_INVOICE: 'SERVICE INDUSTRY',
    USE_OF_PLOT_ACCORDING_TO_FILE: 'SERVICE INDUSTRY',
    Department_Remark: 'Clear',
    Additional_Plot_Count: '0',
    images: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80'],
    has_pdf: true,
    has_map: true
  },
  {
    ID: '104',
    NAME_OF_NODE: 'KHARGHAR',
    SECTOR_NO_: '10',
    BLOCK_ROAD_NAME: 'Main Ave',
    PLOT_NO_: '22',
    PLOT_NO_AFTER_SURVEY: '22',
    SUB_PLOT_NO_: 'A',
    UID: 'UID-2023-004',
    DATE_OF_ALLOTMENT: '2018-03-12',
    NAME_OF_ORIGINAL_ALLOTTEE: 'Green Homes',
    PLOT_AREA_SQM_: '1000.00',
    PLOT_AREA_FOR_INVOICE: '1000.00',
    PLOT_USE_FOR_INVOICE: 'RESIDENTIAL + COMMERCIAL',
    USE_OF_PLOT_ACCORDING_TO_FILE: 'RESIDENTIAL + COMMERCIAL',
    Department_Remark: 'Legal Issue',
    Additional_Plot_Count: '2',
    images: [],
    has_pdf: true,
    has_map: false
  },
  {
    ID: '105',
    NAME_OF_NODE: 'KHARGHAR',
    SECTOR_NO_: '10',
    BLOCK_ROAD_NAME: 'Main Ave',
    PLOT_NO_: '23',
    PLOT_NO_AFTER_SURVEY: '23',
    SUB_PLOT_NO_: '',
    UID: 'UID-2023-005',
    DATE_OF_ALLOTMENT: '2019-11-05',
    NAME_OF_ORIGINAL_ALLOTTEE: 'City Infra',
    PLOT_AREA_SQM_: '800.00',
    PLOT_AREA_FOR_INVOICE: '800.00',
    PLOT_USE_FOR_INVOICE: 'RESIDENTIAL',
    USE_OF_PLOT_ACCORDING_TO_FILE: 'RESIDENTIAL',
    Department_Remark: 'Clear',
    Additional_Plot_Count: '0',
    images: [],
    has_pdf: false,
    has_map: false
  }
];
